avoid date classes not getting respected by stopifnot, fixes #213
christophsax/tsbox pull request #214
Opened 2022-07-19 07:03 UTC by mbannert

## Description
regularize date helpers used ONLY the first element of the vectore returned by class. Hence if a Date had multiple classes like many advanced date objects have, stopifnot caused an error. data.table adds *iDate* on top of a standard date class while preserving the standard Date class. Because *Date* is only the second element of the class vector, it's not respected, *iDate* is not known and the function crashes despite the fact that the input is a perfectly fine date. 

## Related Issue

fix #213  

## Example

see diff, it's only a small change and the diffs shows exactly what happens.

2022-07-19 08:35 UTC, christophsax requested changes

2022-07-19 08:35 UTC, christophsax commented on R/date_helpers.R
> +  stopifnot(inherits(x,c("POSIXct", "Date")))
Nice! I wasn't aware that `inherits()` can have multiple classes. 

Can you follow the style guide and add a space after `x`?

2022-07-25 10:20 UTC, mbannert commented
I guess you mean a space after the comma. Did that, hope it's fine now. .

2022-07-25 12:55 UTC, christophsax approved these changes

2022-07-25 12:56 UTC, merged